### ISSUE TITLE
Temp drop using first layer temp

### ISSUE THREAD

**Issue by wmoore64** [workinghard/mmuGcodeParser#3]
Hi, first of all thanks for your hard work on this. I am currently using your script to print the MMU-Testobject with 3 different colors of the same SUNLU PLA+ material. I have found that this material is very hard to get to stick on the first layer, and therefor run a first layer temp 10 degrees hotter then all other layers. When I set ram_temp_diff_wait_for_stabilize = True, the script appears to use the first layer temp, drops 10 degrees and is then at the same temp its extruding at for all the layers, instead of dropping an additional 10 before unloading. In watching the print for several hours I haven't seen it change temps at all. Is there an easy way to wait to set the initTemp variable until after the first layer? Thanks very much.

**Comment by workinghard** [comment]
@wmoore64 It looks like there is a bug for the first layer. I also saw some strange behavior in regards to that. Independent of that the reason why the temp is not changing is because you're using most likely same profile for all 3 colors. 
In order to trigger the script to do something, the temperatures need to be different. Otherwise it's assuming same material, and no intervention is required. Just create three different profiles with 1C difference and then it should work as expected.

**Comment by wmoore64** [comment]
You're right, same profile for all 3. Thanks for the solution and extremely
fast response!

Cheers,
Bill

**Comment by workinghard** [comment]
I’m glad that helped.
